version: '3.1'
services:
    leanote:
      image: xxyl80/leanote
      restart: always
      ports:
        - "9000:9000"
      volumes:
        - /nasdata/leanote/conf/app.conf:/app/leanote/conf/app.conf
        - /nasdata/leanote/public/upload/:/app/leanote/data/public/upload/
        - /nasdata/leanote/files:/app/leanote/files/
      links:
        - mongo

    mongo:
      image: mongo:3.6
      restart: always
      volumes:
        - /nasdata/mongodb/data:/data/db
        - /nasdata/mongodb/configdb:/data/configdb

    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 3320:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: mongo@7952.com

    initdb:
      image: mongo:3.6
      links:
        - mongo
      volumes:
        - /nasdata/mongodb/initdb.sh:/initdb.sh
        - /nasdata/mongodb/data:/data/db
      command: sh /initdb.sh